from app.db.models.oficina import Oficina
from app.db.models.cooperativa import Cooperativa
from app.db.models.pagaduria import Pagaduria
from app.db.models.usuario import Usuario
from app.db.models.pensionado import Pensionado
from app.db.models.credito import Credito
from app.db.models.documento import Documento
from app.db.models.historial_credito import HistorialCredito
from app.db.models.refinanciacion import Refinanciacion
from app.db.models.log import Log