"""create initial tables

Revision ID: 3a67bc66d79a
Revises: 
Create Date: 2026-03-21 02:25:23.861976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a67bc66d79a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cooperativas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('edad_minima', sa.Integer(), nullable=False),
    sa.Column('edad_maxima', sa.Integer(), nullable=False),
    sa.Column('monto_minimo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monto_maximo', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('plazo_minimo', sa.Integer(), nullable=False),
    sa.Column('plazo_maximo', sa.Integer(), nullable=False),
    sa.Column('tiempo_minimo_pension', sa.Integer(), nullable=False),
    sa.Column('porcentaje_comision', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oficinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagadurias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pensionados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('celular', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=False),
    sa.Column('fecha_inicio_pension', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oficina_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('contrasena', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('intentos_fallidos', sa.Integer(), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['oficina_id'], ['oficinas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('documento')
    )
    op.create_table('creditos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pensionado_id', sa.Integer(), nullable=False),
    sa.Column('asesor_id', sa.Integer(), nullable=False),
    sa.Column('oficina_id', sa.Integer(), nullable=False),
    sa.Column('cooperativa_id', sa.Integer(), nullable=False),
    sa.Column('pagaduria_id', sa.Integer(), nullable=False),
    sa.Column('nro_libranza', sa.String(length=50), nullable=True),
    sa.Column('tipo_credito', sa.String(length=50), nullable=True),
    sa.Column('monto_solicitado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monto_aprobado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('plazo', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('tasa_mensual', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('valor_cuota', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fecha_desembolso', sa.Date(), nullable=True),
    sa.Column('fecha_fin_estimada', sa.Date(), nullable=True),
    sa.Column('nro_afiliacion', sa.String(length=50), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['asesor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['cooperativa_id'], ['cooperativas.id'], ),
    sa.ForeignKeyConstraint(['oficina_id'], ['oficinas.id'], ),
    sa.ForeignKeyConstraint(['pagaduria_id'], ['pagadurias.id'], ),
    sa.ForeignKeyConstraint(['pensionado_id'], ['pensionados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tabla_afectada', sa.String(length=50), nullable=False),
    sa.Column('registro_afectado', sa.Integer(), nullable=False),
    sa.Column('tipo_accion', sa.String(length=20), nullable=False),
    sa.Column('valores_antes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('valores_despues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credito_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['credito_id'], ['creditos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historial_creditos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credito_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('estado_anterior', sa.String(length=30), nullable=True),
    sa.Column('estado_nuevo', sa.String(length=30), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['credito_id'], ['creditos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refinanciaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credito_id', sa.Integer(), nullable=False),
    sa.Column('obligacion_externa', sa.String(length=100), nullable=True),
    sa.Column('entidad', sa.String(length=100), nullable=True),
    sa.Column('valor_refinanciacion', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('valor_cuota_recoge', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cuotas_recoge', sa.Integer(), nullable=True),
    sa.Column('nro_cuotas_anterior', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['credito_id'], ['creditos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refinanciaciones')
    op.drop_table('historial_creditos')
    op.drop_table('documentos')
    op.drop_table('logs')
    op.drop_table('creditos')
    op.drop_table('usuarios')
    op.drop_table('pensionados')
    op.drop_table('pagadurias')
    op.drop_table('oficinas')
    op.drop_table('cooperativas')
    # ### end Alembic commands ###
