"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ApiError, apiFetch } from "@/lib/api";
import { formatDateTime } from "@/lib/format";
import { readSession, type SessionUser } from "@/lib/session";

type Credito={id:number;estado:string;monto_solicitado:number;monto_aprobado:number|null;tiene_documentos_pendientes:boolean;documentos_pendientes:string|null;created_at:string};
type Seguimiento={id:number;pensionado_nombre:string|null;tipo:string;estado:string;fecha_proximo_contacto:string|null;usuario_nombre:string|null};
type Notificacion={id:number;titulo:string;mensaje:string;href:string;prioridad:string;estado:string;fecha:string};
type Opportunity={credito_id:number;pensionado_nombre:string|null;estado_refinanciacion:string;estado_comercial:string};
type Summary={kpis:{creditos_total:number;creditos_mes:number;creditos_activos:number;creditos_aprobados:number;creditos_aprobados_mes:number;tasa_aprobacion:number;cumpleanos_30_dias:number};creditos_por_estado:Array<{estado:string;total:number}>;productividad_oficinas:Array<{nombre:string;creditos:number}>;productividad_asesoras:Array<{nombre:string;creditos:number}>};

export default function DashboardPage(){
 const [session,setSession]=useState<SessionUser|null>(null),[creditos,setCreditos]=useState<Credito[]>([]),[seguimientos,setSeguimientos]=useState<Seguimiento[]>([]),[notifications,setNotifications]=useState<Notificacion[]>([]),[opportunities,setOpportunities]=useState<Opportunity[]>([]),[summary,setSummary]=useState<Summary|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);
 useEffect(()=>setSession(readSession()),[]);
 useEffect(()=>{if(!session)return;(async()=>{try{const [c,s,n,o,r]=await Promise.all([apiFetch<Credito[]>("/api/v1/creditos/"),apiFetch<Seguimiento[]>("/api/v1/seguimientos/"),apiFetch<{items:Notificacion[]}>("/api/v1/notificaciones/?estado=pendiente&page_size=8"),apiFetch<Opportunity[]>("/api/v1/refinanciaciones/elegibles/"),apiFetch<Summary>("/api/v1/reportes/resumen")]);setCreditos(c);setSeguimientos(s);setNotifications(n.items);setOpportunities(o);setSummary(r)}catch(e){setError(e instanceof ApiError?e.message:"No se pudo cargar el inicio")}finally{setLoading(false)}})()},[session]);
 if(loading||!session)return <State text="Preparando tu espacio de trabajo..."/>;
 if(error)return <State text={error} error/>;
 return session.rol==="administrador"?<AdminHome session={session} summary={summary} notifications={notifications} opportunities={opportunities}/>:<AdvisorHome session={session} credits={creditos} followups={seguimientos} notifications={notifications} opportunities={opportunities}/>;
}

function AdminHome({session,summary,notifications,opportunities}:{session:SessionUser;summary:Summary|null;notifications:Notificacion[];opportunities:Opportunity[]}){
 const k=summary?.kpis;const ready=opportunities.filter(x=>x.estado_refinanciacion==="Listo"&&!['rechazado','convertido'].includes(x.estado_comercial)).length;const maxOffice=Math.max(...(summary?.productividad_oficinas.map(x=>x.creditos)??[1]));
 return <section className="space-y-5"><Hero eyebrow="Visión general" title={`Buenos días, ${session.nombre}`} text="Pulso operativo de la empresa y asuntos que requieren atención." links={[['Ver reportes','/reportes'],['Exportar créditos','/reportes'],['Auditoría','/logs']]}/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Créditos del mes" value={k?.creditos_mes??0} note={`${k?.creditos_total??0} históricos`}/><Metric label="Aprobados del mes" value={k?.creditos_aprobados_mes??0} note={`${k?.tasa_aprobacion??0}% aprobación global`} tone="teal"/><Metric label="Oportunidades disponibles" value={ready} note={`${opportunities.length} entre próximas y activas`} tone="amber"/><Metric label="Alertas pendientes" value={notifications.length} note="Prioridad operativa" tone="rose"/></div><div className="grid gap-4 lg:grid-cols-[1.1fr_.9fr]"><Panel title="Actividad por oficina" subtitle="Créditos visibles por sede">{summary?.productividad_oficinas.length?summary.productividad_oficinas.map(x=><Bar key={x.nombre} label={x.nombre} value={x.creditos} max={maxOffice}/>):<Empty text="Sin actividad por oficina"/>}</Panel><Panel title="Créditos por estado" subtitle="Distribución actual del flujo"><div className="grid grid-cols-2 gap-2">{summary?.creditos_por_estado.map(x=><div key={x.estado} className="rounded-xl bg-stone-50 p-3"><p className="text-xs text-stone-500">{x.estado}</p><p className="mt-1 text-xl font-semibold">{x.total}</p></div>)}</div></Panel></div><Attention items={notifications}/></section>
}

function AdvisorHome({session,credits,followups,notifications,opportunities}:{session:SessionUser;credits:Credito[];followups:Seguimiento[];notifications:Notificacion[];opportunities:Opportunity[]}){
 const now=new Date(),today=now.toISOString().slice(0,10);const accionables=followups.filter(x=>["abierto","pendiente"].includes(x.estado));const overdue=accionables.filter(x=>x.fecha_proximo_contacto&&x.fecha_proximo_contacto.slice(0,10)<today);const todayItems=accionables.filter(x=>x.fecha_proximo_contacto?.slice(0,10)===today);const returned=credits.filter(x=>x.estado.toLowerCase().includes("devuelto"));const docs=credits.filter(x=>x.tiene_documentos_pendientes);const ready=opportunities.filter(x=>x.estado_refinanciacion==="Listo"&&!['rechazado','convertido'].includes(x.estado_comercial));
 return <section className="space-y-5"><Hero eyebrow="Tu jornada" title={`Hola, ${session.nombre}`} text="Empieza por lo vencido, continúa con lo programado y no pierdas oportunidades comerciales." links={[['Nuevo crédito','/creditos'],['Registrar seguimiento','/seguimientos'],['Ver refinanciaciones','/refinanciaciones']]}/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Seguimientos vencidos" value={overdue.length} note="Requieren contacto" tone="rose"/><Metric label="Seguimientos hoy" value={todayItems.length} note="Agenda del día" tone="amber"/><Metric label="Créditos devueltos" value={returned.length} note="Pendientes de corrección"/><Metric label="Para refinanciar" value={ready.length} note="Oportunidades disponibles" tone="teal"/></div><div className="grid gap-4 lg:grid-cols-2"><Panel title="Prioridad de hoy" subtitle="Seguimientos vencidos y programados"><TaskList items={[...overdue,...todayItems].slice(0,6).map(x=>({id:x.id,title:x.pensionado_nombre??`Seguimiento #${x.id}`,detail:x.fecha_proximo_contacto?formatDateTime(x.fecha_proximo_contacto):x.tipo,href:`/seguimientos/${x.id}`}))}/></Panel><Panel title="Créditos que necesitan cuidado" subtitle="Correcciones y documentación"><TaskList items={[...returned.map(x=>({id:x.id,title:`Crédito #${x.id} devuelto`,detail:x.estado,href:`/creditos/${x.id}`})),...docs.map(x=>({id:x.id+100000,title:`Crédito #${x.id} · documentos`,detail:x.documentos_pendientes??"Documentación pendiente",href:`/creditos/${x.id}`}))].slice(0,6)}/></Panel></div><Attention items={notifications}/></section>
}

function Hero({eyebrow,title,text,links}:{eyebrow:string;title:string;text:string;links:string[][]}){return <article className="relative overflow-hidden rounded-3xl border border-teal-900/10 bg-gradient-to-br from-white via-white to-teal-50 p-6 shadow-lg shadow-stone-900/5"><div className="absolute -right-16 -top-20 h-56 w-56 rounded-full bg-amber-300/20 blur-3xl"/><div className="relative flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.24em] text-teal-700">{eyebrow}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-stone-950">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-stone-600">{text}</p></div><div className="flex flex-wrap gap-2">{links.map(([label,href],i)=><Link key={label} href={href} className={i===0?"button-primary":"button-muted"}>{label}</Link>)}</div></div></article>}
function Metric({label,value,note,tone="stone"}:{label:string;value:number;note:string;tone?:string}){const colors:Record<string,string>={stone:"text-stone-950",teal:"text-teal-800",amber:"text-amber-700",rose:"text-rose-700"};return <div className="rounded-2xl border border-stone-800/10 bg-white/85 p-4 shadow-sm"><p className="text-xs font-semibold uppercase tracking-[.15em] text-stone-500">{label}</p><p className={`mt-2 text-3xl font-semibold ${colors[tone]}`}>{value}</p><p className="mt-1 text-xs text-stone-500">{note}</p></div>}
function Panel({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <article className="rounded-2xl border border-stone-800/10 bg-white/85 p-5 shadow-sm"><h2 className="text-lg font-semibold">{title}</h2><p className="mt-1 text-xs text-stone-500">{subtitle}</p><div className="mt-4 space-y-3">{children}</div></article>}
function Bar({label,value,max}:{label:string;value:number;max:number}){return <div><div className="mb-1 flex justify-between text-sm"><span>{label}</span><strong>{value}</strong></div><div className="h-2 overflow-hidden rounded-full bg-stone-100"><div className="h-full rounded-full bg-teal-600/70" style={{width:`${Math.max(5,value/max*100)}%`}}/></div></div>}
function Attention({items}:{items:Notificacion[]}){return <Panel title="Atención operativa" subtitle="Alertas pendientes más recientes"><TaskList items={items.map(x=>({id:x.id,title:x.titulo,detail:x.mensaje,href:x.href}))}/></Panel>}
function TaskList({items}:{items:Array<{id:number;title:string;detail:string;href:string}>}){return items.length?<div className="divide-y divide-stone-800/10">{items.map(x=><Link key={x.id} href={x.href} className="flex items-center justify-between gap-3 py-3 transition hover:text-teal-800"><div><p className="text-sm font-semibold">{x.title}</p><p className="mt-1 line-clamp-1 text-xs text-stone-500">{x.detail}</p></div><span aria-hidden>→</span></Link>)}</div>:<Empty text="Nada pendiente por aquí"/>}
function Empty({text}:{text:string}){return <p className="rounded-xl bg-stone-50 p-5 text-center text-sm text-stone-500">{text}</p>}
function State({text,error=false}:{text:string;error?:boolean}){return <div className={error?"rounded-xl border border-red-200 bg-red-50 p-5 text-sm text-red-700":"rounded-xl border bg-white p-5 text-sm text-stone-500"}>{text}</div>}
