"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ApiError, apiFetch } from "@/lib/api";
import { formatCurrency, formatDate } from "@/lib/format";

type Estado = "programado"|"disponible"|"contactado"|"aceptado"|"rechazado"|"convertido";
type Item={credito_id:number;pensionado_nombre:string|null;documento:string|null;cooperativa_nombre:string|null;monto_aprobado:number|null;fecha_base:string;disponible_desde:string;estado_refinanciacion:string;oportunidad_id:number;estado_comercial:Estado;reactivar_en:string|null;credito_nuevo_id:number|null};
type Vista="hoy"|"proximos"|"gestionados"|"convertidos"|"todos";
const tabs:Array<{key:Vista;label:string}>=[{key:"hoy",label:"Disponibles ahora"},{key:"proximos",label:"Próximos"},{key:"gestionados",label:"En gestión"},{key:"convertidos",label:"Convertidos"},{key:"todos",label:"Todos"}];

export default function RefinanciacionesPage(){
 const [items,setItems]=useState<Item[]>([]),[query,setQuery]=useState(""),[vista,setVista]=useState<Vista>("hoy");
 const [loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[success,setSuccess]=useState<string|null>(null),[savingId,setSavingId]=useState<number|null>(null),[rejecting,setRejecting]=useState<Item|null>(null);
 useEffect(()=>{(async()=>{try{setItems(await apiFetch<Item[]>("/api/v1/refinanciaciones/elegibles/"));}catch(e){setError(e instanceof ApiError?e.message:"No se pudieron cargar las oportunidades");}finally{setLoading(false)}})()},[]);
 const counts=useMemo(()=>({hoy:items.filter(x=>x.estado_refinanciacion==="Listo"&&!['convertido','rechazado'].includes(x.estado_comercial)).length,proximos:items.filter(x=>x.estado_comercial==="programado").length,gestionados:items.filter(x=>['contactado','aceptado','rechazado'].includes(x.estado_comercial)).length,convertidos:items.filter(x=>x.estado_comercial==="convertido").length}),[items]);
 const filtered=useMemo(()=>items.filter(x=>{const matches=vista==="todos"||(vista==="hoy"&&x.estado_refinanciacion==="Listo"&&!['convertido','rechazado'].includes(x.estado_comercial))||(vista==="proximos"&&x.estado_comercial==="programado")||(vista==="gestionados"&&['contactado','aceptado','rechazado'].includes(x.estado_comercial))||(vista==="convertidos"&&x.estado_comercial==="convertido");const term=query.toLowerCase().trim();return matches&&(!term||[x.credito_id,x.pensionado_nombre,x.documento,x.cooperativa_nombre].some(v=>String(v??"").toLowerCase().includes(term)))}),[items,query,vista]);
 async function change(item:Item,estado:Estado,justificacion?:string){setSavingId(item.oportunidad_id);setError(null);setSuccess(null);try{await apiFetch(`/api/v1/refinanciaciones/oportunidades/${item.oportunidad_id}/estado`,{method:"PATCH",body:JSON.stringify({estado,justificacion})});setItems(c=>c.map(x=>x.credito_id===item.credito_id?{...x,estado_comercial:estado,reactivar_en:estado==="rechazado"?new Date(Date.now()+20*86400000).toISOString():null}:x));setSuccess(`Crédito #${item.credito_id}: estado actualizado a ${estado}.`);window.dispatchEvent(new Event("notifications-updated"));}catch(e){setError(e instanceof ApiError?e.message:"No se pudo actualizar la oportunidad");}finally{setSavingId(null)}}
 if(loading)return <Message text="Cargando refinanciaciones..."/>;
 return <section className="space-y-4">
  <header className="rounded-2xl border bg-white/85 p-5"><p className="text-xs font-semibold uppercase tracking-[.22em] text-stone-500">Operación comercial</p><h1 className="mt-2 text-2xl font-semibold">Refinanciaciones</h1><p className="mt-2 text-sm text-stone-600">Oportunidades liberadas según las reglas de cada cooperativa.</p></header>
  {error&&<Message tone="error" text={error}/>}
  {success&&<Message tone="success" text={success}/>}
  <div className="grid gap-3 sm:grid-cols-4"><Metric label="Disponibles ahora" value={counts.hoy}/><Metric label="Próximos" value={counts.proximos}/><Metric label="En gestión" value={counts.gestionados}/><Metric label="Convertidos" value={counts.convertidos}/></div>
  <div className="flex flex-wrap gap-2 border-b pb-3">{tabs.map(t=><button key={t.key} onClick={()=>setVista(t.key)} className={vista===t.key?"rounded-lg bg-teal-950 px-3 py-2 text-sm text-white":"rounded-lg border bg-white px-3 py-2 text-sm text-stone-700"}>{t.label}</button>)}</div>
  <input className="input-base max-w-lg" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar crédito, pensionado, documento o cooperativa"/>
  <div className="overflow-x-auto border-y bg-white/80"><table className="min-w-full text-left text-sm"><thead className="border-b bg-stone-50 text-xs uppercase text-stone-500"><tr>{["Crédito","Pensionado","Cooperativa","TENTATIVA PARA REFI","Estado","Gestión"].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody className="divide-y">{filtered.map(item=><tr key={item.credito_id}><td className="px-4 py-3 font-semibold">#{item.credito_id}</td><td className="px-4 py-3"><p>{item.pensionado_nombre}</p><p className="text-xs text-stone-500">{item.documento}</p></td><td className="px-4 py-3">{item.cooperativa_nombre}</td><td className="px-4 py-3"><p>{formatDate(item.disponible_desde)}</p><p className="text-xs text-stone-500">Base {formatDate(item.fecha_base)} · {formatCurrency(item.monto_aprobado)}</p></td><td className="px-4 py-3"><Badge estado={item.estado_comercial}/>{item.estado_comercial==="rechazado"&&item.reactivar_en?<p className="mt-1 text-xs text-stone-500">Alerta: {formatDate(item.reactivar_en)}</p>:null}</td><td className="px-4 py-3"><div className="flex min-w-72 flex-wrap gap-1.5">{item.estado_refinanciacion==="Listo"&&item.estado_comercial!=="convertido"?<><Action disabled={savingId===item.oportunidad_id} text="Contactado" onClick={()=>void change(item,"contactado")}/><Action disabled={savingId===item.oportunidad_id} text="Aceptado" onClick={()=>void change(item,"aceptado")}/><Action disabled={savingId===item.oportunidad_id} text="Rechazado" onClick={()=>setRejecting(item)}/></>:null}{item.estado_refinanciacion==="Listo"&&!['rechazado','convertido'].includes(item.estado_comercial)?<Link className="button-primary px-2.5 py-1.5 text-xs" href={`/creditos?refinanciar=${item.credito_id}`}>Refinanciar</Link>:null}</div></td></tr>)}{!filtered.length?<tr><td colSpan={6} className="px-4 py-10 text-center text-stone-500">No hay oportunidades en esta vista.</td></tr>:null}</tbody></table></div>
  {rejecting?<RejectModal item={rejecting} saving={savingId===rejecting.oportunidad_id} onClose={()=>setRejecting(null)} onConfirm={async reason=>{await change(rejecting,"rechazado",reason);setRejecting(null)}}/>:null}
 </section>
}
function Badge({estado}:{estado:Estado}){const tone:{[K in Estado]:string}={programado:"bg-sky-50 text-sky-700 border-sky-200",disponible:"bg-emerald-50 text-emerald-700 border-emerald-200",contactado:"bg-amber-50 text-amber-700 border-amber-200",aceptado:"bg-teal-50 text-teal-700 border-teal-200",rechazado:"bg-rose-50 text-rose-700 border-rose-200",convertido:"bg-violet-50 text-violet-700 border-violet-200"};return <span className={`inline-flex rounded-full border px-2.5 py-1 text-xs font-semibold capitalize ${tone[estado]}`}>{estado}</span>}
function Action({text,onClick,disabled}:{text:string;onClick:()=>void;disabled:boolean}){return <button disabled={disabled} onClick={onClick} className="button-muted px-2.5 py-1.5 text-xs disabled:opacity-40">{disabled?"Guardando...":text}</button>}
function RejectModal({item,saving,onClose,onConfirm}:{item:Item;saving:boolean;onClose:()=>void;onConfirm:(reason:string)=>Promise<void>}){const [reason,setReason]=useState("");return <div className="fixed inset-0 z-50 flex items-center justify-center bg-stone-950/35 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-5 shadow-2xl"><h2 className="text-lg font-semibold">Rechazar oportunidad #{item.credito_id}</h2><p className="mt-2 text-sm text-stone-600">La oportunidad seguirá visible y la alerta reaparecerá dentro de 20 días.</p><label className="mt-4 block text-sm font-medium">Motivo<textarea autoFocus className="input-base mt-1 min-h-28" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Explica por qué no continuará ahora"/></label><div className="mt-5 flex justify-end gap-2"><button className="button-muted" disabled={saving} onClick={onClose}>Cancelar</button><button className="button-primary" disabled={saving||!reason.trim()} onClick={()=>void onConfirm(reason.trim())}>{saving?"Guardando...":"Confirmar rechazo"}</button></div></div></div>}
function Metric({label,value}:{label:string;value:number}){return <div className="border-b px-1 py-3"><p className="text-xs uppercase tracking-wider text-stone-500">{label}</p><p className="mt-2 text-xl font-semibold">{value}</p></div>}
function Message({text,tone="default"}:{text:string;tone?:"default"|"error"|"success"}){return <div className={tone==="error"?"border border-red-200 bg-red-50 p-4 text-sm text-red-700":tone==="success"?"border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-700":"border bg-white p-4 text-sm text-stone-500"}>{text}</div>}
